# dotnet core
# Build and test .NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore src
- script: dotnet build src --configuration $(buildConfiguration)
- script: dotnet restore sample
- script: dotnet build sample --configuration $(buildConfiguration)
