# dotnet core
# Build and test .NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore src
  displayName: 'Restore packages for main src'
- script: dotnet build src --configuration $(buildConfiguration)
  displayName: 'Build nuget package '
- script: dotnet publish src --output $(Build.ArtifactStagingDirectory)
  displayName: "Publish artifacts to staging directory (master only)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
- script: dotnet restore sample
  displayName: 'Restore packages for sample projects'
- script: dotnet build sample --configuration $(buildConfiguration)
  displayName: 'Build sample projects'
