# dotnet core
# Build and test .NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  buildConfiguration: 'Release'
  majorVersion: 0
  minorVersion: 0
  patchVersion: 1

name: $(majorVersion).$(minorVersion).$(patchVersion)-ci-$(BuildID)

jobs:
- job: CIBuild
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: dotnet restore src
    displayName: 'Restore packages for main src'
  - script: dotnet build src --configuration $(buildConfiguration)
    displayName: 'Build nuget package '
  - script: dotnet restore sample
    displayName: 'Restore packages for sample projects'
  - script: dotnet build sample --configuration $(buildConfiguration)
    displayName: 'Build sample projects'

- job: PublishArtifacts
  dependsOn: CIBuild
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: grpc/src/AppInsights.Grpc/AppInsights.grpc/AppInsights.grpc.csproj
      versioningScheme: byBuildNumber
      workingDirectory: grpc/src/AppInsights.grpc/AppInsights.grpc

  - task: DotNetCoreCLI@2
    displayName: 'dotnet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: internal
      publishVstsFeed: https://pkgs.dev.azure.com/martinpeck-github/_packaging/AppInsights_grpc/nuget/v3/index.json